name: Build and Push Docker Images

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/llm-models
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        target:
          - { model: qwen2.5-coder, size: 1.5b }
          - { model: qwen2.5-coder, size: 3b }
          - { model: codellama, size: 7b }
          - { model: llama3.2, size: 3b }
          - { model: phi3, size: 3.8b }
        jp: [on, off]

    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          VERSION=$(cat .version)
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Generate Tag
        id: meta
        run: |
          MODEL="${{ matrix.target.model }}"
          SIZE="${{ matrix.target.size }}"
          JP="${{ matrix.jp }}"
          VERSION="${{ steps.version.outputs.version }}"

          # ▼ JPフラグでタグを切り替え（on のときのみ -jp を付ける）
          if [ "$JP" = "on" ]; then
            JP_TAG="-jp"
          else
            JP_TAG=""
          fi

          TAG="${{ env.IMAGE_NAME }}:${MODEL}-${SIZE}${JP_TAG}-${VERSION}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            MODEL_NAME=${{ matrix.target.model }}
            MODEL_SIZE=${{ matrix.target.size }}
            JP_FLAG=${{ matrix.jp }}
            VERSION=${{ steps.version.outputs.version }}
